---

- name: Install locale packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ boss__locales__base_packages }}'
    - '{{ boss__locales__packages }}'

- name: Ensure that specified locales exist
  locale_gen:
    name: '{{ item.name | d(item) }}'
    state: '{{ item.state | d("present") }}'
  with_flattened:
    - '{{ boss__locales__default_list }}'
    - '{{ boss__locales__list }}'
    - '{{ boss__locales__group_list }}'
    - '{{ boss__locales__host_list }}'
    - '{{ boss__locales__dependent_list }}'

- name: Set default system locale
  debconf:
    name: 'locales'
    question: 'locales/default_environment_locale'
    vtype: 'string'
    value: '{{ boss__locales__system_lang }}'
  register: boss__locales__register_system_lang
  when: ansible_pkg_mgr == 'apt' and boss__locales__system_lang|d()

- name: Update /etc/default/locale
  command: 'update-locale LANG={{ boss__locales__system_lang }}'
  when: ansible_pkg_mgr == 'apt' and boss__locales__register_system_lang|changed

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save locale local facts
  template:
    src: 'etc/ansible/facts.d/locales.fact.j2'
    dest: '/etc/ansible/facts.d/locales.fact'
    owner: 'root'
    group: 'root'
    mode: '0755'
  register: boss__locales__register_facts

- name: Update Ansible facts if they were modified
  action: setup
  when: boss__locales__register_facts|changed
